param(
    [string]$SourceUrl = "https://raw.githubusercontent.com/YubaiNya/TouchDX-AndroidClient/main/src/com/Yubai/TouchDX/SvgLoader.java",
    [string]$Output = (Join-Path $PSScriptRoot "..\Limelight\Input\TouchDXRegions.h")
)

$ErrorActionPreference = "Stop"

$source = Invoke-WebRequest -UseBasicParsing -TimeoutSec 60 $SourceUrl
$content = $source.Content
$chunks = $content -split 'Path createPathFromPathData\d* = PathParser\.createPathFromPathData\("'

$regions = New-Object System.Collections.Generic.List[object]

for ($i = 1; $i -lt $chunks.Count; $i++) {
    $chunk = $chunks[$i]
    if ($chunk -notmatch '^(?<path>[^"]+)"\);') {
        continue
    }

    $path = $Matches.path
    $identifier = $null
    if ($chunk -match 'addRegion\([^,]+, "(?<id>[^"]+)"') {
        $identifier = $Matches.id
    }

    if ($identifier -notmatch '^[A-E][1-8]?$') {
        continue
    }

    $offsetX = 0.0
    $offsetY = 0.0
    if ($chunk -match '\.offset\((?<x>-?\d+(?:\.\d+)?)f, (?<y>-?\d+(?:\.\d+)?)f\)') {
        $offsetX = [double]$Matches.x
        $offsetY = [double]$Matches.y
    }

    $regions.Add([pscustomobject]@{
        Identifier = $identifier
        Path = $path
        OffsetX = $offsetX
        OffsetY = $offsetY
    })
}

if ($regions.Count -ne 34) {
    throw "Expected 34 interactive regions, found $($regions.Count)."
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by Tools/GenerateTouchDXRegions.ps1. Do not edit manually.")
$lines.Add("// Geometry is derived from TouchDX-AndroidClient, AGPL-3.0:")
$lines.Add("// https://github.com/YubaiNya/TouchDX-AndroidClient")
$lines.Add("")
$lines.Add("#ifndef TouchDXRegions_h")
$lines.Add("#define TouchDXRegions_h")
$lines.Add("")
$lines.Add("typedef struct {")
$lines.Add("    const char *identifier;")
$lines.Add("    const char *pathData;")
$lines.Add("    CGFloat offsetX;")
$lines.Add("    CGFloat offsetY;")
$lines.Add("} TouchDXRegionDefinition;")
$lines.Add("")
$lines.Add("static const TouchDXRegionDefinition kTouchDXRegionDefinitions[] = {")

foreach ($region in $regions) {
    $escapedPath = $region.Path.Replace("\", "\\").Replace('"', '\"')
    $line = '    {{"{0}", "{1}", {2}, {3}}},' -f `
        $region.Identifier, `
        $escapedPath, `
        $region.OffsetX.ToString("0.#####", [System.Globalization.CultureInfo]::InvariantCulture), `
        $region.OffsetY.ToString("0.#####", [System.Globalization.CultureInfo]::InvariantCulture)
    $lines.Add($line)
}

$lines.Add("};")
$lines.Add("")
$lines.Add("static const NSUInteger kTouchDXRegionDefinitionCount = sizeof(kTouchDXRegionDefinitions) / sizeof(kTouchDXRegionDefinitions[0]);")
$lines.Add("")
$lines.Add("#endif")

$resolvedOutput = [System.IO.Path]::GetFullPath($Output)
$outputDirectory = [System.IO.Path]::GetDirectoryName($resolvedOutput)
[System.IO.Directory]::CreateDirectory($outputDirectory) | Out-Null
[System.IO.File]::WriteAllLines($resolvedOutput, $lines, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $($regions.Count) regions to $resolvedOutput"
